export function createRandomMeshGradients() {
  // Generate random color values
  function randomColor() {
    let hue = Math.floor(Math.random() * 360);
    /* The line `const saturation = Math.floor(Math.random() * 50) + 50; // Minimum saturation of 50%` is
    generating a random value for the saturation of a color. */
    const saturation = /* `Math.floor` is a JavaScript function that rounds a number down to the
        nearest whole number. In the given code, `Math.floor` is used to round
        the random values generated by `Math.random()` to the nearest whole
        number. */
      Math.floor(/* `Math.random()` is a JavaScript function that generates a random decimal number
        between 0 (inclusive) and 1 (exclusive). It is commonly used to generate random
        values for various purposes, such as generating random colors or positions in
        this code. */
        Math.random() * 50) + 50; // Minimum saturation of 50%
    const lightness = Math.floor(Math.random() * 50) + 50; // Minimum lightness of 50%
    // Adjust hue if it falls in the gray range
    if (hue >= 180 && hue <= 240) {
      hue = (hue + 120) % 360;
    }

    return `hsla(${hue},${saturation}%,${lightness}%,1)`;
  }

  // Generate random gradient positions
  function randomPosition() {
    const x = Math.floor(Math.random() * 100);
    const y = Math.floor(Math.random() * 100);
    return `at ${x}% ${y}%`;
  }

  // Generate random mesh gradients
  function generateRandomMeshGradients() {
    const gradients = [];
    for (let i = 0; i < 7; i++) {
      const position = randomPosition();
      const color = randomColor();
      const gradient = `radial-gradient(${position}, ${color} 0px, transparent 50%)`;
      gradients.push(gradient);
    }
    return gradients;
  }

  // Construct the output as JSON
  function constructOutput(gradients) {
    const backgroundColor = randomColor();
    const backgroundImage = gradients.join(',\n');
    return {
      bgColor: backgroundColor,
      bgImage: backgroundImage
    };
  }

  // Generate and return the random mesh gradients as JSON
  const gradients = generateRandomMeshGradients();
  const output = constructOutput(gradients);
  return output;
}
